# Generated by Django 5.1.5 on 2025-02-08 16:47

import conferenceApp.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, validators=[conferenceApp.models.validate_title]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="conference",
            name="age",
        ),
        migrations.AddField(
            model_name="conference",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conference",
            name="price",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Price must be greater than 0"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="conference",
            name="capacity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=1000, message="Capacity cannot exceed 1000"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="conference",
            name="program",
            field=models.FileField(
                upload_to="files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conferences",
                to="conferenceApp.category",
            ),
            preserve_default=False,
        ),
    ]
