# Generated by Django 5.1.5 on 2025-02-13 19:08

import datetime
import django.core.validators
import userApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={"verbose_name": "Participant"},
        ),
        migrations.AlterField(
            model_name="participant",
            name="cin",
            field=models.CharField(
                max_length=8,
                primary_key=True,
                serialize=False,
                validators=[
                    userApp.models.validate_cin,
                    django.core.validators.RegexValidator("[0-9]{8}$", "Invalid Cin"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator,
                    userApp.models.validate_email,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(default=datetime.date(2025, 2, 13)),
        ),
    ]
