# Generated by Django 5.1.5 on 2025-02-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0002_alter_participant_options_alter_participant_cin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
